[project]
name = "rag-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.3.0",
    "faiss-cpu>=1.12.0",
    "orjson>=3.11.4",
    "sentence-transformers>=5.1.2",
]
